import json
import math
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
data = json.load(open(os.path.join(HERE, "data.json")))
LENGTHS = data["lengths"]
NAMES = {"gpt_5_nano": "GPT-5-nano", "qwen3_235b": "Qwen3-235B-A22B"}
MACROS = {"gpt_5_nano": "Nano", "qwen3_235b": "Qwen"}


def mcnemar_p(b10, b01):
    # one-sided exact: P(first-letter wins >= b10 of the discordant pairs | no true difference)
    n = b10 + b01
    return 1.0 if n == 0 else sum(math.comb(n, i) for i in range(b10, n + 1)) / 2 ** n


def fmt_p(p):
    s = "<.001" if p < 0.001 else f"{p:.3f}".replace("0.", ".", 1)
    return r"{\boldmath$" + s + "$}" if p < 0.05 else f"${s}$"


lines = [r"{\footnotesize\setlength{\tabcolsep}{4pt}", r"\begin{tabular}{llcccccc}", r"\toprule",
         r"Model & Length & $n$ & matched & first-letter & $\Delta$ (pp) & $p$ & trace \\",
         r"\midrule"]

for model, cells in data["uplift"].items():
    tot = {"n": 0, "a": 0, "b": 0, "b10": 0, "b01": 0, "tr_sum": 0.0, "tr_n": 0}
    for ln in LENGTHS:
        c = cells[f"len{ln}"]
        p = mcnemar_p(c["b10"], c["b01"])
        delta = 100 * (c["a_correct"] - c["b_correct"]) / c["n"]
        lines.append(" & ".join([
            NAMES[model] if ln == LENGTHS[0] else "", str(ln), str(c["n"]),
            f"{c['b_correct'] / c['n']:.3f}", f"{c['a_correct'] / c['n']:.3f}",
            f"${delta:+.1f}$", fmt_p(p), f"{c['trace_sum'] / c['trace_n']:.2f}"]) + r" \\")
        tot["n"] += c["n"]; tot["a"] += c["a_correct"]; tot["b"] += c["b_correct"]
        tot["b10"] += c["b10"]; tot["b01"] += c["b01"]
        tot["tr_sum"] += c["trace_sum"]; tot["tr_n"] += c["trace_n"]
    lines.append(" & ".join([
        "", r"\emph{pooled}", str(tot["n"]), f"{tot['b'] / tot['n']:.3f}", f"{tot['a'] / tot['n']:.3f}",
        f"${100 * (tot['a'] - tot['b']) / tot['n']:+.1f}$", fmt_p(mcnemar_p(tot["b10"], tot["b01"])),
        f"{tot['tr_sum'] / tot['tr_n']:.2f}"]) + r" \\")
    if model != list(data["uplift"])[-1]:
        lines.append(r"\midrule")

lines += [r"\bottomrule", r"\end{tabular}}"]
with open(os.path.join(HERE, "table.tex"), "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote table.tex")
for line in lines:
    print("  ", line)


def fit_logistic(X, y):
    # Newton/IRLS; columns of X: one intercept per sequence length + trace slope (last)
    b = np.zeros(X.shape[1])
    for _ in range(40):
        p = 1 / (1 + np.exp(-(X @ b)))
        step = np.linalg.solve((X * (p * (1 - p))[:, None]).T @ X, X.T @ (y - p))
        b += step
        if np.abs(step).max() < 1e-8:
            break
    return b


# Does a better-encoded trace go with a more accurate final answer? If the residual uplift
# were carried by the encoding, this slope would be positive. Length-adjusted, because short
# sequences are both easier to track and easier to encode.
rng = np.random.default_rng(0)
macros = []
for model, samples in data["per_completion"].items():
    s = np.array(samples, dtype=float)
    trace, correct, seqlen = s[:, 0], s[:, 1], s[:, 2]
    X = np.column_stack([(seqlen == ln).astype(float) for ln in LENGTHS] + [trace])
    slope = fit_logistic(X, correct)[-1]
    boot = [fit_logistic(X[i], correct[i])[-1] for i in
            (rng.integers(len(s), size=len(s)) for _ in range(1000))]
    lo, hi = np.percentile(boot, [2.5, 97.5])
    print(f"{model}: n={len(s)} length-adjusted trace slope={slope:.3f} 95% CI [{lo:.3f}, {hi:.3f}]")
    tag = MACROS[model]
    macros += [f"\\newcommand{{\\{tag}TraceSlope}}{{{slope:.2f}}}",
               f"\\newcommand{{\\{tag}TraceCI}}{{[{lo:.2f}, {hi:.2f}]}}",
               f"\\newcommand{{\\{tag}TraceN}}{{{len(s)}}}"]

with open(os.path.join(HERE, "stats.tex"), "w") as f:
    f.write("% generated by make_table.py; do not edit\n" + "\n".join(macros) + "\n")
print("wrote stats.tex")
